name: hijaiyah
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  tflite_flutter: ^0.12.1
  image: ^4.8.0
  path_provider: ^2.0.15
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  audioplayers: ^6.4.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/hijaiyah/
    - assets/images/hijaiyah_tracing/
    - assets/images/hijaiyah_gif/
    - assets/hijaiyah_sound/
    - assets/model/hijaiyah_model.tflite
    - assets/model/labels.txt
    - assets/audio/betulsih.mp3
